# Generated by Django 4.2.7 on 2023-11-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blended_classifiers', models.TextField()),
                ('accuracy', models.FloatField()),
                ('kappa', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('confusion_matrix', models.TextField()),
                ('execution_time', models.FloatField()),
                ('total_classifiers', models.IntegerField()),
                ('total_features', models.IntegerField()),
                ('training_data_size', models.IntegerField()),
                ('test_data_size', models.IntegerField()),
                ('random_state', models.IntegerField()),
                ('preprocessing', models.BooleanField()),
                ('smote', models.BooleanField()),
                ('total_cpu_cores', models.IntegerField()),
                ('cpu_usage', models.FloatField()),
                ('total_ram', models.FloatField()),
                ('memory_usage', models.TextField()),
                ('processor_type', models.TextField()),
                ('os_name', models.TextField()),
            ],
        ),
    ]
