# Generated by Django 4.2.7 on 2023-12-07 12:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_analysisresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='datafile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='uploaded_file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.uploadedfile'),
            preserve_default=False,
        ),
    ]
